### ISSUE TITLE
"» twilio-cli encountered an unexpected error" for plugin-multi-call-handling

### ISSUE THREAD

**Issue by twilio-akiramoto** [twilio-professional-services/flex-multi-call-handling#14]
Hello team,
I am not able to start the Flex plugin-multi-call-handling. This is the error I am getting:

C02ZG1SBLVDT:plugin-multi-call-handling akiramoto$ twilio flex:plugins:start -p SalesForceFlexDemo -l debug
[DEBUG] Config File: /Users/akiramoto/.twilio-cli/config.json
[DEBUG] Using profile: SalesForceFlexDemo
[DEBUG] Using Plugins CLI version 4.1.3
[DEBUG] Using Flex Plugins Config File: /Users/akiramoto/.twilio-cli/flex/plugins.json
[DEBUG] Using flex-plugin-scripts version undefined
Using profile SalesForceFlexDemo (AC092de414420fb75c2472d80f2e50cb41)

Checking Flex plugin project directory
[DEBUG] Found command "flex:plugins:start" plugin: @twilio-labs/plugin-flex
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/flex-plugin-builder/issues"
[DEBUG] ENOENT: no such file or directory, open '/Users/akiramoto/Documents/Github/flex-multi-call-handling/plugin-multi-call-handling/node_modules/react/package.json'
[DEBUG] Error: ENOENT: no such file or directory, open '/Users/akiramoto/Documents/Github/flex-multi-call-handling/plugin-multi-call-handling/node_modules/react/package.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.readPackageJson (/Users/akiramoto/.twilio-cli/node_modules/flex-dev-utils/dist/fs.js:123:36)
    at Object.getPaths (/Users/akiramoto/.twilio-cli/node_modules/flex-dev-utils/dist/fs.js:668:38)
    at Object._checkExternalDepsVersions (/Users/akiramoto/.twilio-cli/node_modules/flex-plugin-scripts/dist/scripts/pre-script-check.js:145:40)
    at /Users/akiramoto/.twilio-cli/node_modules/flex-plugin-scripts/dist/scripts/pre-script-check.js:234:29
    at step (/Users/akiramoto/.twilio-cli/node_modules/flex-plugin-scripts/dist/scripts/pre-script-check.js:33:23)
    at Object.next (/Users/akiramoto/.twilio-cli/node_modules/flex-plugin-scripts/dist/scripts/pre-script-check.js:14:53)
    at fulfilled (/Users/akiramoto/.twilio-cli/node_modules/flex-plugin-scripts/dist/scripts/pre-script-check.js:5:58)
C02ZG1SBLVDT:plugin-multi-call-handling akiramoto$

**Comment by twilio-akiramoto** [comment]
Resolved. Had to do configure the .env and set the /public/appConfig.js, run npm install.
